name: Octave Build
# modified from https://www.scivision.dev/windows-matlab-octave-continuous-integration/
# look into a docker image to avoid the octave install...

on:
  pull_request:
    paths:
    - "**.m"
    - ".github/workflows/build-test-octave.yaml"

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: gnuoctave/octave
    steps:
    - uses: actions/checkout@v2      
    - name: Check octave installation
      run: octave --eval "disp(version)"
    - name: Run tests
      run: octave --eval "run_all_tests"
